baseURL: 'http://example.org/'
languageCode: 'en-us'
title: "Axu"
theme: "mini"

# Default content language, support en (English) / zh (Chinese) / nl (Dutch), default 'en'
defaultContentLanguage: 'en'

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  highlight:
    guessSyntax: true
    style: emacs
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # telegram: https://github.com/axuu
  github: https://github.com/axuu
  # twitter: your-github-link
  # stackoverflow: your-github-link
  # facebook: your-facebook-link

# Site parameters
params:
  # Site Author
  author: Axu
  # Author biography
  bio: Every moment matters.
  # Site Description, used in HTML meat
  description: Axu's Blog

  ###########################################
  # Optional Configuration
  ###########################################

  # To enable RSS, you could set `enableRSS: true`, default is `true`
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: false
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: false
  # To enable table of content, you could set `showToc: true`, default is `false`
  showToc: true
  # To hidden powerBy message in the page footer, you could set: `showPowerBy: false`, default is `true`
  showPowerBy: true
  # To enable math typesetting , you could set `math: true`, default is `false`
  math: false
  # To hidden post summary in home page, you could set `hiddenPostSummaryInHomePage: true`, default is `false`
  hiddenPostSummaryInHomePage: false
  # Website copy write, default: '© Copyright 2021 ❤️ {params.author}'
  copyright: © 2021 Axu

  # Extra links in navigation
  links:
    ## e.g.
    # - name: About
      # path: https://www.fredz.cn/

  # You can put your custom css and js to `static` directory, or use remote css and js files which start with `http://` or `https://`
  customCSS:
    - css/custom.css
    # - https://example.com/custom.css # remote css
  customJS:
    ## e.g.
    # - js/custom.js # local js in `static/js/custom.js`
    # - https://example.com/custom.js # remote js